const fs = require('fs');
const path = require('path');
if (fs.existsSync(path.join(__dirname, 'node_modules', 'dotenv'))) require('dotenv').config();
else if (fs.existsSync(path.join(__dirname, '.env'))) require('./scripts/env').loadEnv();
const express = require('express');
const { google } = require('googleapis');
const Database = require('better-sqlite3');
const { randomUUID, randomBytes, scryptSync, timingSafeEqual, createHmac } = require('crypto');
const nanoid = () => randomUUID().replace(/-/g, '').slice(0, 21);
const APP_VERSION = process.env.APP_VERSION || readCommit() || 'dev';
const DB_PATH = process.env.DATABASE_PATH || './data/campstore.sqlite';
const SESSION_SECRET = process.env.SESSION_SECRET || process.env.DEFAULT_OWNER_PASSWORD || 'campstore-dev-session-secret';
const ROLES = { OWNER: 3, ADMIN: 2, CLERK: 1 };
fs.mkdirSync(path.dirname(DB_PATH), { recursive: true });
const db = new Database(DB_PATH);
db.pragma('journal_mode = WAL');
migrate();
const INITIAL_SEED_RESULT = seedDefaultOwner();
const app = express();
app.use(express.json({ limit: '2mb' }));
app.use(express.urlencoded({ extended: false }));
function readCommit(){try{return require('child_process').execSync('git rev-parse --short HEAD',{stdio:['ignore','pipe','ignore']}).toString().trim()}catch{return null}}
function migrate(){
 db.exec(`CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS items(id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE,cost_cents INTEGER NOT NULL,category TEXT NOT NULL DEFAULT 'Uncategorized',active INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS campers(id TEXT PRIMARY KEY,name TEXT NOT NULL,initial_balance_cents INTEGER NOT NULL,current_balance_cents INTEGER NOT NULL,sheet_row INTEGER,updated_at TEXT NOT NULL);
 CREATE INDEX IF NOT EXISTS idx_campers_name ON campers(name);
 CREATE TABLE IF NOT EXISTS transactions(id TEXT PRIMARY KEY,created_at TEXT NOT NULL,clerk TEXT,camper_id TEXT NOT NULL,camper_name TEXT NOT NULL,previous_balance_cents INTEGER NOT NULL,total_cents INTEGER NOT NULL,new_balance_cents INTEGER NOT NULL,items_json TEXT NOT NULL,sync_status TEXT NOT NULL DEFAULT 'pending',synced_at TEXT,error TEXT,FOREIGN KEY(camper_id) REFERENCES campers(id));
 CREATE TABLE IF NOT EXISTS sync_events(id INTEGER PRIMARY KEY AUTOINCREMENT,created_at TEXT NOT NULL,type TEXT NOT NULL,status TEXT NOT NULL,message TEXT);
 CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('OWNER','ADMIN','CLERK')),password_hash TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
 CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);`);
 ensureColumn('items','category',"TEXT NOT NULL DEFAULT 'Uncategorized'");
 setDefault('allow_over_balance', String(process.env.ALLOW_OVER_BALANCE === 'true'));
}
function ensureColumn(table,column,definition){const cols=db.prepare(`PRAGMA table_info(${table})`).all().map(c=>c.name); if(!cols.includes(column)) db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`)}
function setDefault(k,v){db.prepare('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)').run(k,v)}
function seedDefaultOwner(){const existingCount=db.prepare('SELECT count(*) c FROM users').get().c; if(existingCount>0) return {seeded:false,reason:'users-exist'}; const username=process.env.DEFAULT_OWNER_USERNAME, password=process.env.DEFAULT_OWNER_PASSWORD; if(!username||!password) return {seeded:false,reason:'missing-env'}; const display=process.env.DEFAULT_OWNER_DISPLAY_NAME||username; const stamp=now(); db.prepare('INSERT INTO users(id,username,display_name,role,password_hash,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run('user_'+nanoid(),username,display,'OWNER',hashPassword(password),1,stamp,stamp); return {seeded:true,username}}
function hashPassword(password){const salt=randomBytes(16).toString('hex'); const hash=scryptSync(password,salt,64).toString('hex'); return `scrypt$${salt}$${hash}`}
function verifyPassword(password,stored){const [scheme,salt,hash]=String(stored||'').split('$'); if(scheme!=='scrypt'||!salt||!hash) return false; const actual=Buffer.from(hash,'hex'); const check=scryptSync(password,salt,64); return actual.length===check.length && timingSafeEqual(actual,check)}
function sign(value){return createHmac('sha256',SESSION_SECRET).update(value).digest('base64url')}
function makeSession(user){const payload=Buffer.from(JSON.stringify({id:user.id,username:user.username,displayName:user.display_name,role:user.role,exp:Date.now()+1000*60*60*12})).toString('base64url'); return `${payload}.${sign(payload)}`}
function parseCookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').filter(Boolean).map(p=>{const i=p.indexOf('='); return [p.slice(0,i).trim(),decodeURIComponent(p.slice(i+1))]}))}
function currentUser(req){const token=parseCookies(req).campstore_session; if(!token) return null; const [payload,sig]=token.split('.'); if(!payload||sig!==sign(payload)) return null; try{const data=JSON.parse(Buffer.from(payload,'base64url').toString()); if(data.exp<Date.now()) return null; const user=db.prepare('SELECT id,username,display_name,role,active FROM users WHERE id=? AND active=1').get(data.id); return user?{id:user.id,username:user.username,displayName:user.display_name,role:user.role}:null}catch{return null}}
function requireAuth(req,res,next){const user=currentUser(req); if(!user) return wantsHtml(req)?res.redirect('/login.html'):res.status(401).json({error:'Authentication required'}); req.user=user; next()}
function requireRole(...roles){return (req,res,next)=>{if(!req.user) return requireAuth(req,res,()=>requireRole(...roles)(req,res,next)); const min=Math.min(...roles.map(r=>ROLES[r])); if(ROLES[req.user.role]<min) return wantsHtml(req)?res.status(403).send('Forbidden'):res.status(403).json({error:'Forbidden'}); next()}}
function wantsHtml(req){return (req.headers.accept||'').includes('text/html') || !(req.originalUrl||req.path).startsWith('/api/')}
function cents(v){ if (typeof v === 'number') return Math.round(v*100); const s=String(v||'').replace(/[$,]/g,'').trim(); if(!s) throw Error('missing money value'); const n=Number(s); if(Number.isNaN(n)) throw Error('invalid money value '+v); return Math.round(n*100)}
function money(c){return (c/100).toFixed(2)}
function now(){return new Date().toISOString()}

function getSetting(key){return db.prepare('SELECT value FROM settings WHERE key=?').get(key)?.value||''}
function saveSetting(key,value){db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(key,String(value||''))}
function googleConfig(){
 const spreadsheetId=getSetting('google_spreadsheet_id')||process.env.GOOGLE_SPREADSHEET_ID||'';
 const email=getSetting('google_service_account_email')||process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL||'';
 const rawKey=getSetting('google_private_key')||process.env.GOOGLE_PRIVATE_KEY||'';
 const privateKey=rawKey.replace(/\\n/g,'\n');
 return {spreadsheetId,email,privateKey,source:getSetting('google_spreadsheet_id')?'database':'env'};
}
function googleStatus(){const c=googleConfig(); return {configured:!!(c.spreadsheetId&&c.email&&c.privateKey),spreadsheetId:c.spreadsheetId?`configured · ${String(c.spreadsheetId).slice(-4)}`:'missing',serviceAccountEmail:c.email||'',privateKey:c.privateKey?`configured · ${String(c.privateKey).replace(/\n/g,'').slice(-4)}`:'missing',source:c.source,lastImport:getSetting('last_import')||null,lastSync:getSetting('last_sync')||null,pending:db.prepare("SELECT count(*) c FROM transactions WHERE sync_status!='synced'").get().c}}
function sheetsClient(){ const c=googleConfig(); if(!c.spreadsheetId) throw Error('Missing spreadsheet ID'); if(!c.email) throw Error('Missing service account email'); if(!c.privateKey) throw Error('Missing private key'); const auth = new google.auth.JWT(c.email, null, c.privateKey, ['https://www.googleapis.com/auth/spreadsheets']); return {sheets:google.sheets({version:'v4', auth}), spreadsheetId:c.spreadsheetId};}
async function validateSheetTabs(sheets,spreadsheetId,required=['Items','Campers / Balances','Logs']){const meta=await sheets.spreadsheets.get({spreadsheetId,fields:'sheets.properties.title'}); const tabs=new Set((meta.data.sheets||[]).map(s=>s.properties.title)); const missing=required.filter(t=>!tabs.has(t)); if(missing.length) throw Error('Invalid tab names. Missing required tab(s): '+missing.join(', ')); return [...tabs]}
function parseMoneyCell(value,label){try{return cents(value)}catch(e){throw Error(`${label}: ${e.message}`)}}
async function importItems(){const {sheets,spreadsheetId}=sheetsClient(); await validateSheetTabs(sheets,spreadsheetId,['Items']); const r=await sheets.spreadsheets.values.get({spreadsheetId,range:'Items!A2:C'}); const rows=r.data.values||[], warnings=[], byCategory={}; const stamp=now(); let imported=0, skipped=0; const run=db.transaction(()=>{for(const [i,row] of rows.entries()){const rowNum=i+2; if(!row[0]&&!row[1]&&!row[2]){skipped++; continue} const name=String(row[1]||'').trim(); const rawCategory=String(row[2]||'').trim(); if(!name){warnings.push(`Items row ${rowNum}: missing item name; skipped`); skipped++; continue} let cost; try{cost=parseMoneyCell(row[0],`Items row ${rowNum} cost`)}catch(e){warnings.push(`${e.message}; skipped`); skipped++; continue} const category=rawCategory||'Uncategorized'; if(!rawCategory) warnings.push(`Items row ${rowNum} (${name}): missing category; using Uncategorized`); db.prepare('INSERT INTO items(id,name,cost_cents,category,active,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(name) DO UPDATE SET cost_cents=excluded.cost_cents,category=excluded.category,active=1,updated_at=excluded.updated_at').run('item_'+nanoid(),name,cost,category,1,stamp); byCategory[category]=(byCategory[category]||0)+1; imported++}}); run(); saveSetting('last_import',stamp); const warningText=warnings.length?`; warnings: ${warnings.length}`:''; event('import_items','ok',`Imported ${imported} items; skipped ${skipped} rows${warningText}`); return {ok:true,imported,skipped,warnings,byCategory,lastImport:stamp}}
async function importCampers(){const {sheets,spreadsheetId}=sheetsClient(); await validateSheetTabs(sheets,spreadsheetId,['Campers / Balances']); const r=await sheets.spreadsheets.values.get({spreadsheetId,range:'Campers / Balances!A2:C'}); const rows=r.data.values||[], seen=new Set(), warnings=[]; const stamp=now(); let imported=0, skipped=0; const run=db.transaction(()=>{for(const [i,row] of rows.entries()){if(!row[0]&&!row[1]&&!row[2]){skipped++; continue} if(!row[0]) throw Error(`Campers / Balances row ${i+2}: missing child name`); const name=String(row[0]).trim(); const key=name.toLowerCase(); if(seen.has(key)) throw Error('Duplicate camper name: '+name); seen.add(key); const initial=parseMoneyCell(row[1],`Campers / Balances row ${i+2} initial balance`); const current=parseMoneyCell(row[2],`Campers / Balances row ${i+2} current balance`); db.prepare('INSERT INTO campers(id,name,initial_balance_cents,current_balance_cents,sheet_row,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,initial_balance_cents=excluded.initial_balance_cents,current_balance_cents=excluded.current_balance_cents,sheet_row=excluded.sheet_row,updated_at=excluded.updated_at').run('camper_'+Buffer.from(key).toString('hex').slice(0,32),name,initial,current,i+2,stamp); imported++}}); run(); saveSetting('last_import',stamp); event('import_campers','ok',`Imported ${imported} campers; skipped ${skipped} blank rows`); return {ok:true,imported,skipped,warnings,lastImport:stamp}}
async function syncPending(){const {sheets,spreadsheetId}=sheetsClient(); await validateSheetTabs(sheets,spreadsheetId,['Campers / Balances','Logs']); const pending=db.prepare("SELECT * FROM transactions WHERE sync_status!='synced' ORDER BY created_at").all(); for(const t of pending){await sheets.spreadsheets.values.append({spreadsheetId,range:'Logs!A:I',valueInputOption:'USER_ENTERED',requestBody:{values:[[t.created_at,t.clerk,t.camper_name,money(t.previous_balance_cents),money(t.total_cents),money(t.new_balance_cents),JSON.parse(t.items_json).map(i=>`${i.qty}x ${i.name} @ $${money(i.price_cents)}`).join('; '),t.id,'synced']]}}); const camper=db.prepare('SELECT sheet_row FROM campers WHERE id=?').get(t.camper_id); if(camper?.sheet_row) await sheets.spreadsheets.values.update({spreadsheetId,range:`Campers / Balances!C${camper.sheet_row}`,valueInputOption:'USER_ENTERED',requestBody:{values:[[money(t.new_balance_cents)]]}}); db.prepare("UPDATE transactions SET sync_status='synced',synced_at=?,error=NULL WHERE id=?").run(now(),t.id)} const stamp=now(); saveSetting('last_sync',stamp); event('sync','ok',`Synced ${pending.length} transactions`); return {ok:true,synced:pending.length,lastSync:stamp}}
function event(type,status,message){db.prepare('INSERT INTO sync_events(created_at,type,status,message) VALUES(?,?,?,?)').run(now(),type,status,message||'')}
app.get('/login.html',(req,res)=>res.sendFile(path.join(__dirname,'public','login.html')));
app.get('/login',(req,res)=>res.redirect('/login.html'));
app.post('/api/login',(req,res)=>{const {username,password}=req.body||{}; const user=db.prepare('SELECT * FROM users WHERE username=? AND active=1').get(String(username||'')); if(!user||!verifyPassword(String(password||''),user.password_hash)) return res.status(401).json({error:'Invalid username or password'}); res.cookie('campstore_session',makeSession(user),{httpOnly:true,sameSite:'lax',secure:process.env.COOKIE_SECURE==='true',maxAge:1000*60*60*12}); res.json({ok:true,user:{username:user.username,displayName:user.display_name,role:user.role}})});
app.post('/api/logout',(req,res)=>{res.clearCookie('campstore_session'); res.json({ok:true})});
app.get('/api/me',requireAuth,(req,res)=>res.json({user:req.user}));
app.get('/',requireAuth,(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.get('/index.html',requireAuth,(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.get('/admin.html',requireAuth,requireRole('ADMIN','OWNER'),(req,res)=>res.sendFile(path.join(__dirname,'public','admin.html')));
app.use(express.static(path.join(__dirname, 'public'), { index: false }));
app.use('/api',requireAuth);
app.get('/api/state',(req,res)=>{res.json({user:req.user,items:db.prepare('SELECT * FROM items WHERE active=1 ORDER BY name').all(),campers:db.prepare('SELECT * FROM campers ORDER BY name').all(),settings:Object.fromEntries(db.prepare('SELECT key,value FROM settings').all().map(r=>[r.key,r.value])),pending:db.prepare("SELECT count(*) c FROM transactions WHERE sync_status!='synced'").get().c,version:APP_VERSION})});
app.get('/api/transactions',requireRole('ADMIN','OWNER'),(req,res)=>res.json(db.prepare('SELECT * FROM transactions ORDER BY created_at DESC LIMIT 200').all().map(t=>({...t,items:JSON.parse(t.items_json)}))));
app.post('/api/settings',requireRole('ADMIN','OWNER'),(req,res)=>{for(const [k,v] of Object.entries(req.body||{})) db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(k,String(v)); res.json({ok:true})});
app.post('/api/sale',(req,res)=>{try{const {camperId, cart, allowOverride}=req.body; const camper=db.prepare('SELECT * FROM campers WHERE id=?').get(camperId); if(!camper) return res.status(404).json({error:'Camper not found'}); if(!Array.isArray(cart)||!cart.length) return res.status(400).json({error:'Cart is empty'}); const items=cart.map(ci=>{const item=db.prepare('SELECT * FROM items WHERE id=? AND active=1').get(ci.id); if(!item) throw Error('Item not found'); const qty=Math.max(1,Number(ci.qty)||1); return {id:item.id,name:item.name,price_cents:item.cost_cents,qty,line_total_cents:item.cost_cents*qty}}); const total=items.reduce((a,i)=>a+i.line_total_cents,0); const allow=db.prepare("SELECT value FROM settings WHERE key='allow_over_balance'").get()?.value==='true'; if(camper.current_balance_cents-total<0 && !allow && !allowOverride) return res.status(409).json({error:'Purchase exceeds current balance'}); const txid='tx_'+nanoid(); const created=now(); const run=db.transaction(()=>{db.prepare('UPDATE campers SET current_balance_cents=?,updated_at=? WHERE id=?').run(camper.current_balance_cents-total,created,camper.id); db.prepare('INSERT INTO transactions(id,created_at,clerk,camper_id,camper_name,previous_balance_cents,total_cents,new_balance_cents,items_json) VALUES(?,?,?,?,?,?,?,?,?)').run(txid,created,req.user.displayName,camper.id,camper.name,camper.current_balance_cents,total,camper.current_balance_cents-total,JSON.stringify(items));}); run(); res.json({ok:true,id:txid,camperId:camper.id,new_balance_cents:camper.current_balance_cents-total})}catch(e){res.status(400).json({error:e.message})}});

app.get('/api/settings/google',requireRole('ADMIN','OWNER'),(req,res)=>res.json(googleStatus()));
app.post('/api/settings/google',requireRole('ADMIN','OWNER'),(req,res)=>{try{let {spreadsheetId,serviceAccountEmail,privateKey,serviceAccountJson}=req.body||{}; if(serviceAccountJson){const parsed=typeof serviceAccountJson==='string'?JSON.parse(serviceAccountJson):serviceAccountJson; spreadsheetId=spreadsheetId||parsed.spreadsheet_id||parsed.spreadsheetId; serviceAccountEmail=serviceAccountEmail||parsed.client_email; privateKey=privateKey||parsed.private_key} spreadsheetId=String(spreadsheetId||'').trim(); serviceAccountEmail=String(serviceAccountEmail||'').trim(); privateKey=String(privateKey||'').trim(); if(!spreadsheetId) return res.status(400).json({error:'Missing spreadsheet ID'}); if(!serviceAccountEmail) return res.status(400).json({error:'Missing service account email'}); if(!privateKey && !getSetting('google_private_key') && !process.env.GOOGLE_PRIVATE_KEY) return res.status(400).json({error:'Missing private key'}); saveSetting('google_spreadsheet_id',spreadsheetId); saveSetting('google_service_account_email',serviceAccountEmail); if(privateKey) saveSetting('google_private_key',privateKey); res.json({ok:true,google:googleStatus()})}catch(e){res.status(400).json({error:'Invalid service account JSON: '+e.message})}});
app.post('/api/google/test',requireRole('ADMIN','OWNER'),async(req,res)=>{try{const {sheets,spreadsheetId}=sheetsClient(); const tabs=await validateSheetTabs(sheets,spreadsheetId); event('google_test','ok','Google Sheets connection test succeeded'); res.json({ok:true,message:'Google Sheets connection successful',tabs,status:googleStatus()})}catch(e){event('google_test','error',e.message); res.status(400).json({error:e.message,status:googleStatus()})}});
app.post('/api/google/import/items',requireRole('ADMIN','OWNER'),async(req,res)=>{try{res.json(await importItems())}catch(e){event('import_items','error',e.message); res.status(400).json({error:e.message})}});
app.post('/api/google/import/campers',requireRole('ADMIN','OWNER'),async(req,res)=>{try{res.json(await importCampers())}catch(e){event('import_campers','error',e.message); res.status(400).json({error:e.message})}});
app.post('/api/google/import/all',requireRole('ADMIN','OWNER'),async(req,res)=>{try{const items=await importItems(); const campers=await importCampers(); res.json({ok:true,items,campers})}catch(e){event('import_all','error',e.message); res.status(400).json({error:e.message})}});
app.post('/api/google/sync-pending',requireRole('ADMIN','OWNER'),async(req,res)=>{try{res.json(await syncPending())}catch(e){event('sync','error',e.message); db.prepare("UPDATE transactions SET sync_status='error',error=? WHERE sync_status!='synced'").run(e.message); res.status(400).json({error:e.message})}});
app.post('/api/import',requireRole('ADMIN','OWNER'),async(req,res)=>{try{const items=await importItems(); const campers=await importCampers(); res.json({ok:true,items,campers})}catch(e){event('import','error',e.message); res.status(400).json({error:e.message})}});
app.post('/api/sync',requireRole('ADMIN','OWNER'),async(req,res)=>{try{res.json(await syncPending())}catch(e){event('sync','error',e.message); db.prepare("UPDATE transactions SET sync_status='error',error=? WHERE sync_status!='synced'").run(e.message); res.status(400).json({error:e.message})}});
app.get('/api/status',requireRole('ADMIN','OWNER'),async(req,res)=>{let gs=googleStatus(); const today=new Date().toISOString().slice(0,10); res.json({database:{path:DB_PATH,ok:true},stats:{campers:db.prepare('SELECT count(*) c FROM campers').get().c,items:db.prepare('SELECT count(*) c FROM items WHERE active=1').get().c,itemsByCategory:db.prepare('SELECT category,count(*) c FROM items WHERE active=1 GROUP BY category ORDER BY category').all(),salesToday:db.prepare("SELECT count(*) c FROM transactions WHERE substr(created_at,1,10)=?").get(today).c,revenueToday:db.prepare("SELECT coalesce(sum(total_cents),0) c FROM transactions WHERE substr(created_at,1,10)=?").get(today).c},googleStatus:gs.configured?'configured':'not configured',google:gs,lastImport:gs.lastImport,lastSync:gs.lastSync,pending:gs.pending,version:APP_VERSION,events:db.prepare('SELECT * FROM sync_events ORDER BY id DESC LIMIT 30').all()})});
app.get('/api/users',requireRole('OWNER'),(req,res)=>res.json(db.prepare('SELECT id,username,display_name,role,active,created_at,updated_at FROM users ORDER BY username').all()));
app.post('/api/users',requireRole('OWNER'),(req,res)=>{const {username,password,displayName,role}=req.body||{}; if(!username||!password||!ROLES[role]) return res.status(400).json({error:'username, password, and role are required'}); const stamp=now(); db.prepare('INSERT INTO users(id,username,display_name,role,password_hash,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run('user_'+nanoid(),username,displayName||username,role,hashPassword(password),1,stamp,stamp); res.json({ok:true})});
app.post('/api/users/:id/password',requireRole('OWNER'),(req,res)=>{if(!req.body?.password) return res.status(400).json({error:'password is required'}); db.prepare('UPDATE users SET password_hash=?,updated_at=? WHERE id=?').run(hashPassword(req.body.password),now(),req.params.id); res.json({ok:true})});
if (require.main === module) app.listen(process.env.PORT||3077,()=>console.log(`Camp Store POS running on ${process.env.PORT||3077}`));
module.exports = { app, db, hashPassword, migrate, seedDefaultOwner, initialSeedResult: INITIAL_SEED_RESULT };
